from __future__ import annotations

import hashlib
import re
import zipfile
from pathlib import Path

from docx import Document as WordDocument
from docx.table import Table
from docx.text.paragraph import Paragraph
from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE_TYPE
from pypdf import PdfReader


# XML 1.0 / python-docx rejects most C0 control characters, DEL and lone
# surrogates. Normalize them at ingestion so exported citations are always safe.
_XML_INVALID = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f\ud800-\udfff]")


def _clean_text(raw: str) -> str:
    text = _XML_INVALID.sub(" ", raw.replace("\r", ""))
    return re.sub(r"[ \t]+", " ", text).strip()


def _chart_text(chart) -> list[str]:
    texts: list[str] = []
    if getattr(chart, "has_title", False):
        try:
            texts.append(chart.chart_title.text_frame.text)
        except (AttributeError, ValueError):
            pass
    for plot in chart.plots:
        try:
            for category in plot.categories:
                label = getattr(category, "label", None)
                if label:
                    texts.append(str(label))
        except (AttributeError, ValueError):
            pass
    for series in chart.series:
        name = getattr(series, "name", None)
        if name:
            texts.append(str(name))
    return texts


def _pptx_shape_text(shape) -> list[str]:
    texts: list[str] = []
    if getattr(shape, "has_text_frame", False):
        texts.append(shape.text)
    if getattr(shape, "has_table", False):
        texts.extend(" | ".join(cell.text for cell in row.cells) for row in shape.table.rows)
    if getattr(shape, "has_chart", False):
        texts.extend(_chart_text(shape.chart))
    if getattr(shape, "shape_type", None) == MSO_SHAPE_TYPE.GROUP:
        for child in shape.shapes:
            texts.extend(_pptx_shape_text(child))
    return texts


def _pptx_slide_text(slide) -> str:
    texts: list[str] = []
    for shape in slide.shapes:
        texts.extend(_pptx_shape_text(shape))
    return "\n".join(texts).strip()


def parse_document(path: Path, doc_id: str, name: str) -> list[dict]:
    """Parse supported text; source identifiers and offsets are never generated by an LLM."""
    suffix = path.suffix.lower()
    units = []
    if suffix in (".docx", ".pptx"):
        with zipfile.ZipFile(path) as archive:
            if sum(i.file_size for i in archive.infolist()) > 100 * 1024 * 1024:
                raise ValueError("解压后内容过大，请缩小资料")
    if suffix == ".pdf":
        reader = PdfReader(path)
        if reader.is_encrypted:
            raise ValueError("加密 PDF 无法处理，请先解除密码")
        if len(reader.pages) > 300:
            raise ValueError("单份 PDF 最多 300 页")
        for n, page in enumerate(reader.pages, 1):
            text = page.extract_text() or ""
            if not text.strip():
                raise ValueError(f"第 {n} 页没有可提取文字，可能是扫描页；请转为文字型资料后上传")
            units.append((text, {"kind": "pdf", "page_number": n, "block_index": 1}))
    elif suffix == ".pptx":
        deck = Presentation(path)
        if len(deck.slides) > 300:
            raise ValueError("课件最多 300 页")
        for n, slide in enumerate(deck.slides, 1):
            text = _pptx_slide_text(slide)
            # Image-only slides (for example a chart screenshot) are common in
            # otherwise text-based decks. Skip just that slide instead of
            # rejecting the whole course file.
            if text:
                units.append((text, {"kind": "pptx", "slide_number": n}))
        if not units:
            raise ValueError("课件中没有可提取文字，可能是图片型课件；请提供文字型课件")
    elif suffix == ".docx":
        doc = WordDocument(path)
        paragraph_index = table_index = 0
        for block in doc.iter_inner_content():
            if isinstance(block, Paragraph):
                paragraph_index += 1
                if block.text.strip():
                    units.append((block.text, {"kind": "docx", "paragraph_index": paragraph_index}))
            elif isinstance(block, Table):
                table_index += 1
                for row_index, row in enumerate(block.rows, 1):
                    for cell_index, cell in enumerate(row.cells, 1):
                        if cell.text.strip():
                            units.append((cell.text, {"kind": "docx", "table_index": table_index, "row_index": row_index, "cell_index": cell_index}))
        if len(units) > 1000:
            raise ValueError("Word 资料最多 1,000 个段落／单元格")
    else:
        raise ValueError("仅支持文字型 PDF、PPTX、DOCX")
    if not units or sum(len(u[0]) for u in units) > 300000:
        raise ValueError("没有可提取文本，或提取文本超过 30 万字符")
    chunks = []
    for unit_index, (raw, locator) in enumerate(units, 1):
        text = _clean_text(raw)
        for part_index, start in enumerate(range(0, len(text), 1000)):
            fragment = text[start:start + 1000]
            chunk_id = f"{doc_id}_u{unit_index}_c{part_index}"
            segments = []
            for sentence_index, match in enumerate(re.finditer(r"[^。！？\n]+[。！？\n]?", fragment), 1):
                if not match.group().strip():
                    continue
                segments.append({"source_id": f"{chunk_id}_s{sentence_index}", "paragraph_id": f"u{unit_index}", "text": match.group(), "span_start": match.start(), "span_end": match.end(), "locator": locator})
            chunks.append({"id": chunk_id, "document_id": doc_id, "document_name": name, "locator": locator, "text": fragment, "text_hash": hashlib.sha256(fragment.encode()).hexdigest(), "segments": segments, "parser_version": "1", "segmenter_version": "1"})
    return chunks
