// Run against tests.serve_browser_fixture on 8791, not a real user's workspace.
// PLAYWRIGHT_MODULE may point at a bundled playwright installation.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || '../frontend/node_modules/playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  const browser = await chromium.launch({channel: process.env.PLAYWRIGHT_CHANNEL || 'chrome', headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1050}});
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8791');
  await page.getByRole('button',{name:'新建项目',exact:true}).click();
  await page.getByRole('button',{name:/没有资料？试用原创数据库讲义/}).click();
  await page.locator('.file-item').filter({hasText:'分析完成'}).waitFor({timeout:30000});
  await page.getByRole('button',{name:'AI 组卷规划',exact:true}).click();
  await page.getByRole('heading',{name:'先看方案，再开始出题',exact:true}).waitFor();
  await page.getByPlaceholder('例如：增加事务的考察比重，把索引的题目改为中等难度。').fill('把事务安排为主要知识点');
  await page.getByRole('button',{name:'发送调整要求',exact:true}).click();
  await page.getByText('规划 Agent · 第 2 版方案 · 还没有生成具体题目',{exact:true}).waitFor();
  await page.getByRole('button',{name:'确认方案并出题',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.exam-layout .question-card').length===13,{},{timeout:30000});
  await page.getByRole('button',{name:'生成 Word 双版本',exact:true}).waitFor();
  await page.locator('.exam-layout .question-card').first().getByRole('button',{name:'删除后补题',exact:true}).click();
  await page.getByRole('dialog',{name:'把这道题，一起打磨好'}).waitFor();
  const drawer=page.getByRole('dialog',{name:'把这道题，一起打磨好'});
  await drawer.locator('.chat-compose textarea').fill('换成事务原子性的难简答题，分数不变');
  await drawer.getByRole('button',{name:'生成候选',exact:true}).click();
  await drawer.locator('.candidate-preview').waitFor({timeout:30000});
  assert.equal(await page.locator('.exam-layout .question-card').count(),12);
  await drawer.locator('.chat-compose textarea').fill('请把解释写得更清楚');
  await drawer.getByRole('button',{name:'继续修改',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.chat-message.assistant').length===2);
  await drawer.locator('.candidate-preview').getByRole('button',{name:/原文依据/}).click();
  await page.getByRole('dialog',{name:'原文依据',exact:true}).waitFor();
  await page.getByRole('dialog',{name:'原文依据',exact:true}).getByRole('button',{name:'关闭',exact:true}).click();
  await drawer.getByRole('button',{name:'采纳这道题',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.exam-layout .question-card').length===13 && !document.querySelector('.vacancy-card'));
  await page.getByRole('button',{name:'生成 Word 双版本',exact:true}).click();
  await page.getByRole('link',{name:/下载纯试卷/}).waitFor();
  assert.equal(await page.locator('.download-card').count(),2);
  const downloadEvent=page.waitForEvent('download');
  await page.getByRole('link',{name:/下载纯试卷/}).click();
  const download=await downloadEvent;
  fs.mkdirSync('data/browser-check',{recursive:true});
  await download.saveAs(path.join('data/browser-check',download.suggestedFilename()));
  await page.screenshot({path:'data/browser-check/full-workflow.png',fullPage:true});
  await page.getByRole('button',{name:'执行记录',exact:true}).click();
  await page.getByRole('dialog',{name:'执行记录',exact:true}).waitFor();
  await page.screenshot({path:'data/browser-check/traces.png',fullPage:true});
  assert.deepEqual(errors,[]);
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('dialog',{name:'执行记录',exact:true}).getByRole('button',{name:'关闭',exact:true}).click();
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.screenshot({path:'data/browser-check/mobile.png',fullPage:true});
  await browser.close();
  console.log('PASS: browser upload → analysis → plan revision → 13 questions → deletion → 2 candidate turns → source drawer → adoption → Word download; no JS errors; mobile no horizontal overflow. Model responses are test doubles; MCP and app are real.');
})().catch(e=>{console.error(e);process.exit(1)});
